const mongoose = require('mongoose');

const asistenteSchema = new mongoose.Schema({
	rut: Number,
	clave: String,
	rol: Number,
	nombre: String,
	fecha_nac: String,
	edad: String,
	direccion: String,
	comuna: String,
	region: String,
	nacionalidad: String,
	telefono: String,
	correo: String,
	sexo:String,
	asignado:Number,
	//formulario 1
	inscripcion: String,
	diagnostico: String,
	alergias:String,
	contextura:String,
	//Formulario 2
	prevision:{
		fonasa: Boolean,
      	banmedica: Boolean,
     	colmena:Boolean,
      	cruzblanca:Boolean,
     	nuevamasvida:Boolean,
      	capredena: Boolean,
     	dipreca: Boolean,
		Otro: Boolean,
		Cual: String,
	},
	afp: String,
	afp_nombre: String,
	ano_escolaridad: String,
	nvl_escolar: String,
	ano_ulti_nvl: String,
	profesion: String,
	
	//formulario3
	pref_asis: String,
	discapacidad: {
		fisica:Boolean,
		intelectual: Boolean,
		psiquica:Boolean,
		visual:Boolean,
		auditiva:Boolean,
		},
	grado: String,
	
	//formulario 4
	p_aseo:{
		lavar_cuerpo: Boolean,
		ducharse: Boolean,
		cepillar_dientes: Boolean,
		maquillar: Boolean,
		afeitar: Boolean,
		depilar: Boolean,
		aplicar_crema: Boolean,
		peinar: Boolean,
		t_a_otra:Boolean,
		t_a_cual:String
	},
	p_ciclo:{
		levantarse_cama: Boolean,
		vestirse : Boolean,
		desvestirse : Boolean,
		poner_pijama: Boolean,
		acostarse: Boolean,
		t_ci_otra: Boolean,
		t_ci_cual: String
	},
	p_fisio:{
		ayuda_comer: Boolean,
		ayuda_beber: Boolean,
		apoyo_limpieza_orinar: Boolean,
		apoyo_limpieza_defecar: Boolean,
		t_f_otra:Boolean,
		t_f_cual:String,
	},
	p_salud:{
		prep_toma_medicamento: Boolean,
		ayuda_tecnica: Boolean,
		t_s_otra:Boolean,
		t_s_cual:String
	},
	p_atencion:{
		responder_tel: Boolean,
		tomar_nota: Boolean,
		pasar_pag: Boolean,
		acomodar_pc_acces: Boolean,
		acomodar_cel_acces: Boolean,
		t_ate_otra:Boolean,
		t_ate_cual:String,
	},
	p_cuidado:{
		atencion_hijos:Boolean,
		atencion_sobrinos:Boolean,
		atencion_nietos:Boolean,
		t_cu_otra:Boolean,
		t_cu_cual:String
	},
	h_limp:{
		aseo_hogar:Boolean,
		lavado_vajilla:Boolean,
		lavado_ropa:Boolean,
		limp_muebles:Boolean,
		limp_banos:Boolean,
		hacer_cama:Boolean,
		barrer:Boolean,
		aspirar:Boolean,
		planchar:Boolean,
		h_otra:Boolean,
		h_cual:String
	},
	h_orden:{
		organizar_objetos_h:Boolean,
		guardar_ropa:Boolean,
		guardar_ropa_cama:Boolean,
		guardar_zapatos:Boolean,
		org_deco:Boolean,
		t_o_otra:Boolean,
		t_o_cual:String
	},
	h_alimentacion:{
		prep_desayuno:Boolean,
		prep_merienda:Boolean,
		prep_almuerzo:Boolean,
		prep_once:Boolean,
		prep_cena:Boolean,
		uso_electro:Boolean,
		t_ali_otra:Boolean,
		t_ali_cual:String
	},
	h_cuidado:{
		atender_animal:Boolean,
		atender_planta:Boolean,
		h_cuidado_otra:Boolean,
		h_cuidado_cual:String
	},
	a_acompanar:{
		acompanamiento_vivienda:Boolean,
		acompanamiento_otra:Boolean,
		acompanamiento_cual:String
	},
	a_ocupacion:{
		acompanar_traslado_trabajo:Boolean,
		acompanar_traslado_estudio:Boolean,
		acompanar_traslado_comunitaria:Boolean,
		asist_acti_laboral:Boolean,
		asist_acti_educativa:Boolean,
		asist_acti_comunitaria:Boolean,
		ocupacion_otra:Boolean,
		ocupacion_cual:String
	},
	a_gestion:{
		realizar_tramites:Boolean,
		ir_banco:Boolean,
		ir_medico:Boolean,
		compras_super:Boolean,
		compras_tiendas:Boolean,
		gestion_otra:Boolean,
		gestio_cual:String,
	},
	a_oscio:{
		viaje_dentro_pais:Boolean,
		viajes_fuera_pais:Boolean,
		acompanar_vacacion:Boolean,
		asistir_conciertos:Boolean,
		asistir_cine:Boolean,
		asistir_teatros:Boolean,
		asistir_restaurant:Boolean,
		oscio_otra:Boolean,
		oscio_cual:String,
		},
	conduccion:{
		asis_conduce_buscar_persona_disc:Boolean,
		asis_conduce_buscar_tercero:Boolean,
		asistencia_conduccion:Boolean,
		condu_otra:Boolean,
		condu_cual:String,
	},
	comunicacion:{
		comu_tableros:Boolean,
		comu_dispositivo:Boolean,
		comu_otra:Boolean,
		comu_cual:String,
	},
	cordinacion:{
		establecer_cumplir_agenda:Boolean,
		coor_otra:Boolean,
		coor_cual:String
	},
	excepcion:{
		situ_crisis_persona:Boolean,
		excepcion:Boolean,
		excepcion_cual:String
	},
	//formulario 6
	lunes:{
		Lu_primero: Boolean,
		Lu_segundo: Boolean,
		Lu_tercero: Boolean,
		Lu_cuarto: Boolean,
		Lu_quinto: Boolean,
		Lu_sexto: Boolean,
		Lu_septimo: Boolean,
		Lu_octavo: Boolean,
		Lu_noveno:Boolean,
		Lu_decimo:Boolean,
		Lu_undecimo:Boolean,
		Lu_duodecimo:Boolean,
		Lu_decimotercero:Boolean,
	},
	martes:{
		Ma_primero: Boolean,
		Ma_segundo: Boolean,
		Ma_tercero: Boolean,
		Ma_cuarto: Boolean,
		Ma_quinto: Boolean,
		Ma_sexto: Boolean,
		Ma_septimo: Boolean,
		Ma_octavo: Boolean,
		Ma_noveno:Boolean,
		Ma_decimo:Boolean,
		Ma_undecimo:Boolean,
		Ma_duodecimo:Boolean,
		Ma_decimotercero:Boolean,
	},

	miercoles:{
		Mi_primero: Boolean,
		Mi_segundo: Boolean,
		Mi_tercero: Boolean,
		Mi_cuarto: Boolean,
		Mi_quinto: Boolean,
		Mi_sexto: Boolean,
		Mi_septimo: Boolean,
		Mi_octavo: Boolean,
		Mi_noveno:Boolean,
		Mi_decimo:Boolean,
		Mi_undecimo:Boolean,
		Mi_duodecimo:Boolean,
		Mi_decimotercero:Boolean,
	},
	jueves:{
		Ju_primero: Boolean,
		Ju_segundo: Boolean,
		Ju_tercero: Boolean,
		Ju_cuarto: Boolean,
		Ju_quinto: Boolean,
		Ju_sexto: Boolean,
		Ju_septimo: Boolean,
		Ju_octavo: Boolean,
		Ju_noveno:Boolean,
		Ju_decimo:Boolean,
		Ju_undecimo:Boolean,
		Ju_duodecimo:Boolean,
		Ju_decimotercero:Boolean,
	},
	viernes:{
		Vi_primero: Boolean,
		Vi_segundo: Boolean,
		Vi_tercero: Boolean,
		Vi_cuarto: Boolean,
		Vi_quinto: Boolean,
		Vi_sexto: Boolean,
		Vi_septimo: Boolean,
		Vi_octavo: Boolean,
		Vi_noveno:Boolean,
		Vi_decimo:Boolean,
		Vi_undecimo:Boolean,
		Vi_duodecimo:Boolean,
		Vi_decimotercero:Boolean,
	},
	sabado:{
		Sa_primero: Boolean,
		Sa_segundo: Boolean,
		Sa_tercero: Boolean,
		Sa_cuarto: Boolean,
		Sa_quinto: Boolean,
		Sa_sexto: Boolean,
		Sa_septimo: Boolean,
		Sa_octavo: Boolean,
		Sa_noveno:Boolean,
		Sa_decimo:Boolean,
		Sa_undecimo:Boolean,
		Sa_duodecimo:Boolean,
		Sa_decimotercero:Boolean,
	},
	domingo:{
		Do_primero: Boolean,
		Do_segundo: Boolean,
		Do_tercero: Boolean,
		Do_cuarto: Boolean,
		Do_quinto: Boolean,
		Do_sexto: Boolean,
		Do_septimo: Boolean,
		Do_octavo: Boolean,
		Do_noveno:Boolean,
		Do_decimo:Boolean,
		Do_undecimo:Boolean,
		Do_duodecimo:Boolean,
		Do_decimotercero:Boolean,
	},
	

});

module.exports = mongoose.model('Asistente', asistenteSchema);
